### PR TITLE
Fix template color & texture bug

### PR DESCRIPTION
**Pull request by diosamuel**
Hello @vsoch 👋

# Problem
The Candy always reset to plain template when i choose another template & texture, so i must choose texture again

i have fixed this bug, also i change a little bit the color of the template & color picker, so the color picker and color of the candy synced

please kindly review my PR😁, thankyou

### CODE REVIEW

**Review by vsoch — CHANGES_REQUESTED** [review]
This is fantastic, and badly needed! I just tested and the functionality is correct. I have one request before merge - I was rather fond of the original brown color `#482f1e` because I found that it matched a traditional candy bar wrapper color very well. I would like to request changing the defaults in the candy.json back to this original color, and then have the color chooser just default to the brown instead of purple. Would that be ok? Thank you!

**Comment by diosamuel** [comment]
Allright thanks for the review, i'll change that

and for the font color, is that ok?

**Comment by diosamuel** [comment]
i've change it, please review my PR @vsoch

**Review by vsoch — APPROVED** [review]
Perfecto!

**Comment by vsoch** [comment]
And I like the font default as white as well - that makes sense given that it starts that way.

**Pull request merged**
